// Package plan loads and saves fleet-plan.txt.
package plan

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
)

const (
	ShapeMicro = "VM.Standard.E2.1.Micro"
	ShapeA1    = "VM.Standard.A1.Flex"
	MaxBootGB  = 200
	A1OCPUs    = 2
	A1MemoryGB = 12
)

// Entry is one planned instance.
type Entry struct {
	Name     string
	Shape    string
	OCPUs    int // 0 when unused (Micro)
	MemoryGB int // 0 when unused (Micro)
	BootGB   int
}

// Plan is the full fleet plan file.
type Plan struct {
	Interval string // e.g. 15m, 30m, 1h, 12h, 24h
	Entries  []Entry
}

// Arch returns "x86" or "aarch64" for image selection.
func (e Entry) Arch() string {
	if e.Shape == ShapeA1 {
		return "aarch64"
	}
	return "x86"
}

// SumBootGB returns total boot volume GB across entries.
func (p *Plan) SumBootGB() int {
	sum := 0
	for _, e := range p.Entries {
		sum += e.BootGB
	}
	return sum
}

// FindIndex returns the index of an entry by name, or -1.
func (p *Plan) FindIndex(name string) int {
	for i, e := range p.Entries {
		if e.Name == name {
			return i
		}
	}
	return -1
}

// ValidateEntry checks shape / boot / A1 fixed config and boot sum ≤ MaxBootGB.
// excludeIdx is the index being replaced (-1 for add).
func (p *Plan) ValidateEntry(e Entry, excludeIdx int) error {
	if strings.TrimSpace(e.Name) == "" {
		return fmt.Errorf("名稱不可空白")
	}
	if e.Shape != ShapeMicro && e.Shape != ShapeA1 {
		return fmt.Errorf("不支援的 shape: %s（僅 %s 或 %s）", e.Shape, ShapeMicro, ShapeA1)
	}
	if e.BootGB <= 0 {
		return fmt.Errorf("boot_gb 必須 > 0")
	}
	if e.Shape == ShapeA1 {
		if e.OCPUs != A1OCPUs || e.MemoryGB != A1MemoryGB {
			return fmt.Errorf("A1.Flex 固定為 %d OCPU / %dGB", A1OCPUs, A1MemoryGB)
		}
	} else {
		e.OCPUs = 0
		e.MemoryGB = 0
	}
	sum := e.BootGB
	for i, ex := range p.Entries {
		if i == excludeIdx {
			continue
		}
		sum += ex.BootGB
	}
	if sum > MaxBootGB {
		return fmt.Errorf("boot_gb 總和 %d > %d（Always Free 上限）", sum, MaxBootGB)
	}
	// duplicate name check
	for i, ex := range p.Entries {
		if i == excludeIdx {
			continue
		}
		if ex.Name == e.Name {
			return fmt.Errorf("名稱已存在: %s", e.Name)
		}
	}
	return nil
}

// Load reads a fleet-plan.txt from path.
func Load(path string) (*Plan, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	p := &Plan{Interval: "15m"}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "interval=") {
			p.Interval = strings.TrimSpace(strings.TrimPrefix(line, "interval="))
			continue
		}
		parts := strings.Split(line, "|")
		if len(parts) < 5 {
			return nil, fmt.Errorf("無效列: %s（格式 name|shape|ocpus|memory_gb|boot_gb）", line)
		}
		e := Entry{
			Name:  strings.TrimSpace(parts[0]),
			Shape: strings.TrimSpace(parts[1]),
		}
		if s := strings.TrimSpace(parts[2]); s != "" {
			n, err := strconv.Atoi(s)
			if err != nil {
				return nil, fmt.Errorf("ocpus 無效: %s", s)
			}
			e.OCPUs = n
		}
		if s := strings.TrimSpace(parts[3]); s != "" {
			n, err := strconv.Atoi(s)
			if err != nil {
				return nil, fmt.Errorf("memory_gb 無效: %s", s)
			}
			e.MemoryGB = n
		}
		boot, err := strconv.Atoi(strings.TrimSpace(parts[4]))
		if err != nil {
			return nil, fmt.Errorf("boot_gb 無效: %s", parts[4])
		}
		e.BootGB = boot
		if e.Shape == ShapeA1 {
			if e.OCPUs == 0 {
				e.OCPUs = A1OCPUs
			}
			if e.MemoryGB == 0 {
				e.MemoryGB = A1MemoryGB
			}
		}
		p.Entries = append(p.Entries, e)
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	return p, nil
}

// Save writes the plan to path.
func Save(path string, p *Plan) error {
	var b strings.Builder
	b.WriteString("# fleet-plan.txt — generated by oracle-free-setup\n")
	b.WriteString("interval=" + p.Interval + "\n")
	b.WriteString("# name|shape|ocpus|memory_gb|boot_gb\n")
	for _, e := range p.Entries {
		ocpus, mem := "", ""
		if e.Shape == ShapeA1 {
			ocpus = strconv.Itoa(e.OCPUs)
			mem = strconv.Itoa(e.MemoryGB)
		}
		fmt.Fprintf(&b, "%s|%s|%s|%s|%d\n", e.Name, e.Shape, ocpus, mem, e.BootGB)
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// IntervalChoices returns supported interval labels and cron-friendly values.
func IntervalChoices() []struct {
	Label string
	Value string
} {
	return []struct {
		Label string
		Value string
	}{
		{"15 分鐘", "15m"},
		{"30 分鐘", "30m"},
		{"1 小時", "1h"},
		{"12 小時", "12h"},
		{"24 小時", "24h"},
	}
}

// CronSpec returns a 5-field cron expression for Asia/Taipei intervals.
func CronSpec(interval string) (string, error) {
	switch strings.ToLower(strings.TrimSpace(interval)) {
	case "15m", "15min":
		return "*/15 * * * *", nil
	case "30m", "30min":
		return "*/30 * * * *", nil
	case "1h", "1H", "60m":
		return "0 * * * *", nil
	case "12h", "12H":
		return "0 */12 * * *", nil
	case "24h", "24H", "1d":
		return "0 0 * * *", nil
	default:
		return "", fmt.Errorf("不支援的 interval: %s", interval)
	}
}
